# Generated by Django 3.1.3 on 2020-11-20 01:06

import cashbackapi.apps.cashback.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='document',
            field=models.CharField(max_length=11, unique=True, validators=[cashbackapi.apps.cashback.validators.validate_cpf]),
        ),
    ]
